const SAVE_DATA = 'SAVE_DATA';
const EDIT_DATA = 'EDIT_DATA';
const SAVE_EDITED_DATA = 'SAVE_EDITED_DATA';
const DELETE_DATA = 'DELETE_DATA';
const CANCEL_EDIT = 'CANCEL_EDIT';
const CHANGE_SERVICE_NAME = 'CHANGE_SERVICE_NAME';
const CHANGE_SERVICE_PRICE = 'CHANGE_SERVICE_PRICE';
const FILTER_DATA = 'FILTER_DATA';
const DELETE_FILTERED_DATA = 'DELETE_FILTERED_DATA';

export {
    SAVE_DATA,
    EDIT_DATA,
    DELETE_DATA,
    CANCEL_EDIT,
    CHANGE_SERVICE_NAME,
    CHANGE_SERVICE_PRICE,
    SAVE_EDITED_DATA,
    FILTER_DATA,
    DELETE_FILTERED_DATA
}